
export const INFORMACION_COVER_SUCCESSFUL = 'INFORMACION_COVER_SUCCESSFUL';
export const INFORMACION_COVER_ERROR = 'INFORMACION_COVER_ERROR';

export const SEARCH_SOUND_SUCCESSUL = 'SEARCH_SOUND_SUCCESSUL';
export const SEARCH_SOUND_ERROR = 'SEARCH_SOUND_ERROR';

export const PLAY_SOUND_SUCCESSULL = 'PLAY_SOUND_SUCCESSULL';
export const PLAY_SOUND_ERROR = 'PLAY_SOUND_ERROR';

export const DISPLAY_REPRODUCTOR_SUCCESSULL = 'DISPLAY_REPRODUCTOR_SUCCESSULL';

export const SUBIR_VOLUMEN_SUCCESSFULL = 'SUBIR_VOLUMEN_SUCCESSFULL';
export const PLAYING_OK = 'PLAYING_OK';
export const TOOGLE_ADD ='TOOGLE_ADD';

export const SPINNER_ADD = 'SPINNER_ADD';
export const CLEAR_SOUND_ARRAY = 'CLEAR_SOUND_ARRAY';

export const ADD_REPRO_OK = 'ADD_REPRO_OK'

/*type user*/
export const USER_LOGIN_SUCCESSFULLY =  'USER_LOGIN_SUCCESSFULLY';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_CREATE_SUCCESSFULL = 'USER_CREATE_SUCCESSFULL';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';

export const USER_LOGOUT = 'USER_LOGOUT';

export const CLEAN_ALERT = 'CLEAN_ALERT';


